name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake contribution grid
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Pratik-Dungano
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00FFFF,#00BFFF,#00008B,#9400D3,#FFA500,#FF4500,#FF0000,#FF69B4,#00FFFF&color_dots=#ebedf0,#c6e48b,#7bc96f,#239a3b&color_background=transparent

      - name: Push the SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
