name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Pratik-Dungano
          outputs: |
            dist/github-contribution-grid-snake.svg
          config: |
            theme: dark
            color_snake: "#00BFFF,#00008B,#FFA500,#FF0000"
            color_dots: "#444c56,#2f363d,#1c2128,#0d1117"  # GitHub dark theme tones
            color_background: "#0d1117"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
