name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake animation (neon with transparency)
        uses: Platane/snk@v3
        with:
          github_user_name: Pratik-Dungano
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2300FFFF,%2300BFFF,%2300008B,%239400D3,%23FFA500,%23FF4500,%23FF0000,%23FF69B4,%2300FFFF&color_dots=%23ebedf0,%23c6e48b,%237bc96f,%23239a3b&color_background=transparent

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
