name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Pratik-Dungano
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2300BFFF,%2300008B,%23FFA500,%23FF0000&color_dots=%23444c56,%232f363d,%231c2128,%230d1117&color_background=%230d1117

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
