name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Pratik-Dungano
          outputs: |
            dist/github-contribution-grid-snake.svg
          config: |
            theme: default
            color_snake: "#FF0000"
            color_dots: "#C0C0C0,#808080,#404040,#000000"  # grid shade levels
            color_background: "#000000"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
