name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake animation with neon gradient and transparent background
        uses: Platane/snk@v3
        with:
          github_user_name: Pratik-Dungano
          outputs: |
            dist/github-contribution-grid-snake.svg
          args: >
            --color_snake "#00FFFF,#00BFFF,#0000FF,#8A2BE2,#FF00FF,#FF1493,#FF4500,#FF0000,#00FFFF"
            --color_dots "#d6e685,#8cc665,#44a340,#1e6823"
            --color_background "transparent"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
